### ISSUE TITLE
Investigate Connecting to HydroShare Account

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2512]
- [x] Find documentation for this on [hydroshare.org](https://www.hydroshare.org). It does not seem to be included in their [API Swagger site](https://www.hydroshare.org/hsapi/).
- [x] See if they have a staging site, that we could use for testing integration.
- [x] OAuth login needs a Client ID and a Client Secret that MMW will have to use. Procure this from the client and save in LastPass.

May need to work with @ajrobbins on this.

**Comment by rajadain** [comment]
OAuth integration documentation is here: https://github.com/hydroshare/hydroshare/wiki/HydroShare-REST-API#oauth-20-support

**Comment by rajadain** [comment]
I've registered a test app with HydroShare credentials with the following settings:

```yaml
name: mmw-test
client-id: XXX
client-secret: XXXYYYZZZ
client-type: confidential
grant-type: authorization-code

authorization-url: https://www.hydroshare.org/o/authorize/
access-token-url: https://www.hydroshare.org/o/token/
```

The redirect URLs for this service require an HTTPS address, thus we may have to arrange for localhost to be HTTPS approved.
